{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac43f334-9490-403f-898d-3bd372f81b39",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import * #GUI design\n",
    "import datetime as dt\n",
    "import time\n",
    "import winsound as ws\n",
    "from threading import Thread\n",
    "\n",
    "# Global control variables\n",
    "stop_alarm = False\n",
    "snooze_time = None\n",
    "\n",
    "def start_alarm_thread():\n",
    "    t1 = Thread(target=alarm)\n",
    "    t1.start()\n",
    "\n",
    "def alarm():\n",
    "    global stop_alarm, snooze_time\n",
    "    stop_alarm = False\n",
    "    snooze_time = None\n",
    "\n",
    "    while True:\n",
    "        if stop_alarm:   # if stop button pressed\n",
    "            break\n",
    "\n",
    "        set_time = f\"{hour.get()}:{minute.get()}:{second.get()} {ampm.get()}\"\n",
    "        time.sleep(1)\n",
    "\n",
    "        # Current time in 12-hour format with AM/PM\n",
    "        curr_time = dt.datetime.now().strftime('%I:%M:%S %p')\n",
    "\n",
    "        if snooze_time and curr_time == snooze_time:  # snooze triggered\n",
    "            ws.PlaySound(\"D:\\\\alarmsong.wav\", ws.SND_ASYNC)#to play sound on alarm\n",
    "            snooze_time = None\n",
    "\n",
    "        elif curr_time == set_time:   # normal alarm trigger\n",
    "            ws.PlaySound(\"D:\\\\alarmsong.wav\", ws.SND_ASYNC)\n",
    "            set_time = None   # alarm stops checking once it rings\n",
    "\n",
    "\n",
    "def stop_alarm_sound():\n",
    "    global stop_alarm\n",
    "    stop_alarm = True\n",
    "    ws.PlaySound(None, ws.SND_PURGE)   # stop any sound immediately\n",
    "\n",
    "def snooze_alarm():\n",
    "    global snooze_time\n",
    "    # Add 5 minutes to current time\n",
    "    snooze_dt = dt.datetime.now() + dt.timedelta(minutes=1)\n",
    "    snooze_time = snooze_dt.strftime('%I:%M:%S %p')\n",
    "    ws.PlaySound(None, ws.SND_PURGE)   # stop current ringing\n",
    "    print(\"Snoozed until:\", snooze_time)\n",
    "\n",
    "# def update_time():\n",
    "#      curr_time = dt.datetime.now().strftime('%I:%M:%S %p')\n",
    "#      current_time_label.config(text=f\"Current Time: {curr_time}\")\n",
    "#     Alarm.after(1000, update_time)\n",
    "\n",
    "# Tkinter Window\n",
    "Alarm = Tk()\n",
    "Alarm.geometry('600x450')\n",
    "Alarm.title(\"Alarm Clock\")\n",
    "\n",
    "Label(Alarm, text=\"My Alarm Clock\", font=(\"Calibri\", 20, \"bold\"), fg='green').pack(pady=10)\n",
    "Label(Alarm, text=\"Set time\", font=(\"Calibri\", 16, \"bold\"), fg='blue').pack()\n",
    "\n",
    "frame = Frame(Alarm)\n",
    "frame.pack()\n",
    "\n",
    "# Hours (12-hour format)\n",
    "hour = StringVar(Alarm)\n",
    "hours = tuple(f\"{i:02}\" for i in range(1, 13))\n",
    "hour.set(hours[0])\n",
    "hr = OptionMenu(frame, hour, *hours)\n",
    "hr.pack(side=LEFT)\n",
    "\n",
    "# Minutes\n",
    "minute = StringVar(Alarm)\n",
    "minutes = tuple(f\"{i:02}\" for i in range(60))\n",
    "minute.set(minutes[0])\n",
    "mins = OptionMenu(frame, minute, *minutes)\n",
    "mins.pack(side=LEFT)\n",
    "\n",
    "# Seconds\n",
    "second = StringVar(Alarm)\n",
    "seconds = tuple(f\"{i:02}\" for i in range(60))\n",
    "second.set(seconds[0])\n",
    "sec = OptionMenu(frame, second, *seconds)\n",
    "sec.pack(side=LEFT)\n",
    "\n",
    "# AM/PM Selection\n",
    "ampm = StringVar(Alarm)\n",
    "ampm.set(\"AM\")\n",
    "ampm_menu = OptionMenu(frame, ampm, \"AM\", \"PM\")\n",
    "ampm_menu.pack(side=LEFT)\n",
    "\n",
    "# Buttons\n",
    "Button(Alarm, text='Set Alarm', font=('Calibri 14 bold'), command=start_alarm_thread).pack(pady=20)\n",
    "Button(Alarm, text='Stop', font=('Calibri 14 bold'), command=stop_alarm_sound, fg=\"red\").pack(pady=5)\n",
    "Button(Alarm, text='Snooze (5 min)', font=('Calibri 14 bold'), command=snooze_alarm, fg=\"blue\").pack(pady=5)\n",
    "\n",
    "# Show current time in window\n",
    "current_time_label = Label(Alarm, font=(\"Calibri\", 14))\n",
    "current_time_label.pack(pady=10)\n",
    "\n",
    "# Alarm.after(1000, update_time)\n",
    "Alarm.mainloop()\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "df399570-95aa-4580-b7c8-c9a8635c7997",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ed6ff11d-4995-47ea-b486-c9455610e179",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
